# ASSIGNMENT 8

# 1. Write a Python Program to Add Two Matrices?

In [6]:
import numpy as np

In [83]:
l1 = np.array([[1,2,3],[3,4,5]])
l2 = np.array([[1,2,3],[3,4,5]])

l3 = l1 + l2

In [84]:
l3

array([[ 2,  4,  6],
       [ 6,  8, 10]])

# 2. Write a Python Program to Multiply Two Matrices?

In [2]:
import numpy as np

In [11]:
def multiply(arr1,arr2,r1,c1,r2,c2):
    arr3 = np.empty((r1,c2),int)
    
    for i in range(r1):
        for j in range(c2):
            sum1 = 0
            for k in range(c1):
                sum1 = sum1 + (arr1[i][k] * arr2[k][j])
            arr3[i][j] = sum1
    return arr3
        
    

In [14]:
#Here first matix creation:
r1 = int(input("Enter a number of rows for matrix first : "))
c1 = int(input("Enter a number of column for matrix first : "))
arr1 = []
for i in range(r1*c1):
    arr1.append(int(input("enter a element : ")))
    
arr1 = np.array(arr1).reshape(r1,c1)

#second matrix creation :
r2 = int(input("Enter a number of rows for matrix second : "))
c2 = int(input("Enter a number of column for matrix second : "))


arr2 = []
for j in range(r2*c2):
    arr2.append(int(input("enter a element : ")))
    
arr2 = np.array(arr2).reshape(r2,c2)

print()

print("matrix first is : ")
print(arr1)
print()

print("matrix second is : ")
print(arr2)
print()


#For matirx multiplication we call funtion
if(c1 == r2):
    arr3 = multiply(arr1,arr2,r1,c1,r2,c2)
    print("After multiplication : ")
    print(arr3)
else:
    print("!!!!!.........Invalid input..............!!!!")
    print()
    print("column of matrix first must be equal to row of second matrix ")

Enter a number of rows for matrix first : 2
Enter a number of column for matrix first : 3
enter a element : 1
enter a element : 2
enter a element : 3
enter a element : 4
enter a element : 5
enter a element : 6
Enter a number of rows for matrix second : 3
Enter a number of column for matrix second : 2
enter a element : 1
enter a element : 2
enter a element : 3
enter a element : 4
enter a element : 5
enter a element : 6

matrix first is : 
[[1 2 3]
 [4 5 6]]

matrix second is : 
[[1 2]
 [3 4]
 [5 6]]

After multiplication : 
[[22 28]
 [49 64]]


# 3. Write a Python Program to Transpose a Matrix?

In [3]:
import numpy as np

In [14]:
def array(r,c):
    lst = []
    for i in range(r*c):
        lst.append(int(input("Enter element : ")))
    
    return np.array(lst).reshape(r,c)


def display(arr):
    return arr
    

In [25]:
#This transpose of matrix is only for square matrix

r = int(input("Enter no of rows : "))
c = int(input("Enter no of columns : "))

arr1 = array(r,c)
print()
print("Before : ")
print(display(arr1))

for i in range(r):
    for j in range(c):
        if(i<=j):
            temp = arr1[i][j]
            arr1[i][j] = arr1[j][i]
            arr1[j][i] = temp
            
print()
print("After : ")
print(display(arr1))
        

Enter no of rows : 3
Enter no of columns : 3
Enter element : 1
Enter element : 2
Enter element : 3
Enter element : 4
Enter element : 5
Enter element : 6
Enter element : 7
Enter element : 8
Enter element : 9

Before : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

After : 
[[1 4 7]
 [2 5 8]
 [3 6 9]]


# 4. Write a Python Program to Sort Words in Alphabetic Order?

In [34]:
word = "Hello, Here i am doing python basic programming assignment "
word = word.lower()
l = word.split()
l.sort()

s = ""
for i in l:
    s = s +" "+i

In [35]:
s

' am assignment basic doing hello, here i programming python'

# 5. Write a Python Program to Remove Punctuation From a String?

In [38]:
string = "Hurray..!!, we won ----- the match...."

l = ['~','`','!','@','#','$','%','^','&','*','(',')','_','-','+','=','{','}',':',';','"',"'",'<',',','>','.','?','/','[','[']
s = ""
for i in string:
    if i in l:
        continue
    s = s+i

In [39]:
s

'Hurray we won  the match'